language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
install:
  - pip install flake8 --use-mirrors
before_script:
  - '[ "$TRAVIS_PYTHON_VERSION" \> 3 ] || flake8 pympler'
script:
  - python setup.py try
  - python setup.py install
  - python setup.py test
