language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
install:
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - "pep8 --ignore=E501,E225 pympler"
  - pyflakes -x W pympler
script:
  - python setup.py try
  - python setup.py install
  - python setup.py test
