language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - sudo apt-get install graphviz python-tk
install:
  - travis_retry pip install Sphinx
  - travis_retry pip install pep8
  - travis_retry pip install coverage
  - travis_retry pip install coveralls
script:
  - coverage run setup.py try
  - python setup.py install
  - python setup.py test
  - python run.py --doctest
  - python run.py --html
after_script:
  - pep8 --exclude=asizeof.py,metadata.py,bottle*.py --max-line-length=80 pympler
after_success:
  - coveralls
